kind: Schedule
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  name: matando-pod
  namespace: squidgame
  annotations:
    experiment.chaos-mesh.org/pause: 'false'
spec:
  schedule: '@every 15s'
  startingDeadlineSeconds: null
  concurrencyPolicy: Forbid
  historyLimit: 1
  type: PodChaos
  podChaos:
    selector:
      namespaces:
        - squidgame
      labelSelectors:
        app: myapp-kafka
    mode: one
    action: pod-failure
    duration: 2m
    gracePeriod: 0