version: "3.9"
services:
  grpcserver:
    build: ./Server
    ports:
      - "50051:50051"
    networks:
      - grpctuiter2

  grpcclient:
    build: ./Client
    environment:
      - CLIENT_HOST=:5000
      - SERVER_HOST=grpcserver:50051
      - NAME=instancia2
    ports:
      - "5002:5000"
    networks:
      - grpctuiter2

networks:
  grpctuiter2:
    driver: "bridge"
